image: jjatria/cpran:latest

variables:
  CPRAN_PREF_DIR: "/builds/$CI_PROJECT_NAMESPACE"

devel:
  variables:
    AUTHOR_TEST: "1"
  script:
    - dzil authordeps --missing | cpanm -nq
    - dzil listdeps   --missing | cpanm -nq
    - dzil test
  tags:
    - cpran
  only:
    - devel

master:
  script:
    - prove -lv
  tags:
    - cpran
  only:
    - master
