image: jjatria/cpran:latest

variables:
  CPRAN_PREF_DIR: "/builds/$CI_PROJECT_NAMESPACE"

devel:
  variables:
    AUTHOR_TEST: "1"
  script:
    - dzil test
  tags:
    - cpran
  only:
    - devel

master:
  script:
    - prove -lv
  tags:
    - cpran
  only:
    - master
