---
abstract: 'A package manager for Praat'
author:
  - 'José Joaquín Atria <jjatria@gmail.com>'
build_requires:
  FindBin: '0'
  Net::EmptyPort: '0'
  Path::Class: '0'
  Plack::App::File: '0'
  Plack::Runner: '0'
  Test::Class::Moose: '0'
  Test::Class::Moose::Load: '0'
  Test::Class::Moose::Role::AutoUse: '0'
  Test::Class::Moose::Runner: '0'
  Test::TCP: '0'
  Try::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPrAN
requires:
  App::Prove: '0'
  Archive::Extract: '0'
  Archive::Tar: '0'
  Array::Utils: '0'
  Capture::Tiny: '0'
  Carp: '0'
  Class::Load: '0'
  Data::Dumper: '0'
  Data::Random::WordList: '0'
  Encode: '0'
  English: '0'
  File::Copy::Recursive: '0'
  File::Path: '0'
  File::Which: '0'
  Getopt::Long: '0'
  Git::Repository: '0'
  Graph: '0.96'
  JSON: '0'
  JSON::Tiny: '0'
  LWP::UserAgent: '0'
  Lingua::EN::Inflexion: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0'
  Moo: '0'
  MooX::HandlesVia: '0'
  MooX::late: '0'
  Moose: '0'
  Moose::Role: '0'
  MooseX::App::Cmd: '0'
  MooseX::App::Cmd::Command: '0'
  MooseX::Getopt: '0'
  MooseX::NonMoose: '0'
  MooseX::Types: '0'
  MooseX::Types::Moose: '0'
  Params::Validate: '0'
  Path::Tiny: '0'
  Regexp::Common: '0'
  Regexp::Common::Email::Address: '1.01'
  SemVer: '0'
  Syntax::Keyword::Try: '0'
  TAP::Harness::Archive: '0'
  Term::ReadKey: '0'
  Text::FormatTable: '0'
  Text::Template: '0'
  Type::Library: '0.008'
  Type::Utils: '0'
  Types::Path::Tiny: '0'
  Types::Standard: '0'
  URI: '0'
  URI::QueryParam: '0'
  YAML::XS: '0'
  if: '0'
  strict: '0'
  uni::perl: '0'
  warnings: '0'
version: '0.04'
x_serialization_backend: 'YAML::Tiny version 1.70'
